### ISSUE TITLE
법칙 차수가 유한해야 한다는 조건을 없애자

### ISSUE THREAD

**Issue by osialfeca** [osialfeca/structure-theory#5]
연속적인 시간축에서의 미분과 관련된 법칙을 정의하려면 시간축에서 어떤 구간에 관해 얘기해야 하는데, 이러면 법칙의 시간 차수가 실수 집합의 카디널리티가 된다. 즉 무한이다. 법칙 차수가 유한해야 한다는 조건이 있으면 이런 경우에 법칙을 만들 수 없게 된다. 이 조건이 없어도 정리들을 다 증명할 수 있을 것 같으므로 그렇게 하자.

**Comment by osialfeca** [comment]
그냥 하지 말자.

**Comment by osialfeca** [comment]
그냥 하지 말자.

**Comment by dragonhailstone** [comment]
또할걸 알고있다.

**Comment by osialfeca** [comment]
잘 아는군

**Comment by osialfeca** [comment]
법칙 차수가 유한하지 않을 때에도 ![math](http://latex.codecogs.com/svg.latex?\mathcal%20R\langle%20k,%20u%20\rangle%20=%20\mathcal%20R[k,%20u])임을 증명하려고 했는데 두 번 실패했다. 배라먹을 자식 딱 보니까 유한하지 않을 때에는 저게 안 된다. 저거랑 저거에 의존하고 있는 정리를 들어내야겠다.

**Comment by osialfeca** [comment]
들어 냈으므로 해결되었다.
